name: 'build-test'
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          coverage-file: dist/example-lcov.info
          minimum-coverage: 80
